removing spaces

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,7 @@ jobs:
     uses: ./.github/workflows/build-wheels.yml
     with:
       # TODO: Add back Python 3.13 when we're ready to move to a more recent version of XLA. 3.13
-      #       fails with a complaint abou the pipes module.
+      #       fails with a complaint about the pipes module.
       python-versions: "3.11,3.12"
       rocm-version: ${{ matrix.rocm-version }}
 
@@ -47,6 +47,7 @@ jobs:
         run: |
           docker run --rm -v "./:/rocm-jax" ubuntu \
             /bin/bash -c "shopt -s dotglob; chown -R $UID /rocm-jax/* || true"
+
       - name: Checkout plugin repo
         uses: actions/checkout@v4
         with:
@@ -67,7 +68,7 @@ jobs:
         run: >
           echo "${{ secrets.GITHUB_TOKEN }}" |
           docker login ghcr.io -u ${{ github.actor }} --password-stdin
-      
+
       - name: ROCm set GPU_FLAG
         id: gpu-config
         shell: bash
@@ -87,11 +88,12 @@ jobs:
           docker run --rm \
             ${{ steps.gpu-config.outputs.device_flag }} \
             "ghcr.io/rocm/jax-ubu22.rocm${ROCM_VERSION//.}:${GITHUB_SHA}" \
-             rocm-smi -a || true
+            rocm-smi -a || true
 
       - name: list files in the wheelhouse
         run: |
           ls -alth ./wheelhouse || true
+
       - name: Run tests
         env:
           GPU_COUNT: "8"
